# Generated by Django 4.1.7 on 2023-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_artist_alter_album_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=50),
        ),
    ]
