
// Mutation Dispatch States
export const CREATE_MUTATION_SUCCESS = 'CREATE_MUTATION_SUCCESS'
export const CREATE_MUTATION_FAIL = 'CREATE_MUTATION_FAIL'
export const DELETE_MUTATION_SUCCESS = 'DELETE_MUTATION_SUCCESS'
export const DELETE_MUTATION_FAIL = 'DELETE_MUTATION_FAIL'


// Query Dispatch States
export const GET_QUERY_SUCCESS = 'GET_QUERY_SUCCESS'
export const GET_QUERY_FAIL = 'GET_QUERY_FAIL'

// Alert Dispatch States
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
